"""Assemble a single readable GDD; source chapters remain authoritative."""
from pathlib import Path
import os,re
root=Path(__file__).resolve().parents[1]; target=root/'docs/GDD_Vireon_FULL.md'
files=[root/'docs/GDD_Vireon.md',*sorted((root/'docs/spec').glob('[0-9][0-9]_*.md')),root/'docs/spec/VALIDATION_REPORT.md']
parts=['<!-- Generated by tools/build_full_gdd.py; edit source chapters instead. -->\n']
for p in files:
 s=p.read_text()
 def fix(m):
  link=m.group(1)
  if '://' in link or link.startswith('#'):return m.group(0)
  path,sep,anchor=link.partition('#')
  rel=os.path.relpath((p.parent/path).resolve(),target.parent).replace(os.sep,'/')
  return ']('+rel+(sep+anchor if sep else '')+')'
 parts.append(re.sub(r'\]\(([^)]+)\)',fix,s))
target.write_text('\n\n---\n\n'.join(parts))
print(f'Compiled {len(files)} sources into {target.name}: {target.stat().st_size} bytes')
