/** Real questbook, production events and IndexedDB; bounded fixtures, not a timing/FPS playtest. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createServer} from 'vite';
await mkdir('artifacts',{recursive:true});
const server=await createServer({server:{host:'127.0.0.1',port:5183,strictPort:true}});await server.listen();let browser;
const report={checks:[],errors:[],layout:[],environment:'Chromium / SwiftShader; actual controls, bounded fixture stock, IndexedDB'};
const check=t=>{report.checks.push(t);console.log('PASS:',t);};
try{
 let launch={headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']};
 if(process.env.VIREON_CHROMIUM_PATH)launch.executablePath=process.env.VIREON_CHROMIUM_PATH;
 browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:844,height:390}});
 await context.addInitScript(()=>{localStorage.setItem('vireon.settings',JSON.stringify({quality:'low',sound:false}));const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=fn=>raf(t=>setTimeout(()=>fn(t),120));});
 const page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 const click=s=>page.$eval(s,e=>e.click()),state=()=>page.evaluate(()=>window.__vireon.getState()),snapshot=()=>page.evaluate(()=>window.__vireon.snapshot());
 const pause=async()=>{await click('#pause-button');await page.evaluate(()=>window.__vireon.save());};
 const shot=async name=>{await page.locator('#quest-panel img').evaluateAll(es=>Promise.all(es.map(e=>e.decode())));await page.waitForTimeout(350);await page.screenshot({path:`artifacts/s25-quest-${name}.png`});};
 await page.goto('http://127.0.0.1:5183');await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#start');await page.waitForFunction(()=>window.__vireon.getState().running);await page.waitForTimeout(2000);
 assert.equal(await page.locator('#objective-text').textContent(),'Дерево развития');await page.keyboard.press('j');assert.equal((await state()).dialog,'quest-panel');assert.equal(await page.locator('.quest-node').count(),19);assert.deepEqual((await state()).quests.completed,[]);await page.setViewportSize({width:1366,height:768});await click('#quest-fit');const ticks=(await state()).activeTicks;await page.waitForTimeout(450);assert.equal((await state()).activeTicks,ticks);await shot('fresh');check('HUD / J opens all 19 goals, no fabricated starter achievements; reading pauses active game time');
 await page.locator('[data-quest="air"]').click();assert.deepEqual(await page.locator('.quest-parent').evaluateAll(es=>es.map(e=>e.dataset.quest)),['dome','distributor','oxygen']);assert.equal(await page.locator('.quest-condition').count(),3);assert.match(await page.locator('#quest-detail').textContent(),/384 GU/);await page.locator('.quest-condition').filter({hasText:'Купол'}).click();assert.equal((await state()).questBook.selected,'dome');await page.keyboard.press('Escape');assert.equal((await state()).dialog,'quest-panel');await page.keyboard.press('Escape');assert.equal((await state()).running,true);check('AND conditions reveal the three actual air-system prerequisites; parent navigation and two-level Escape work');
 await pause();await page.setViewportSize({width:844,height:390});await page.evaluate(async()=>{const {addItems}=await import('/src/game/inventory.ts');const s=window.__vireon.snapshot();addItems(s.player.inventory,'stone',4);addItems(s.player.inventory,'fiber',2);window.__vireon.setState(s);});await click('#resume');await page.keyboard.press('b');await click('[data-recipe="craft_tool_stone"]');await page.locator('.craft-primary').click();await page.waitForFunction(()=>!window.__vireon.getState().base.hand);await click('#close-production');await page.keyboard.press('j');assert.ok((await state()).quests.completed.includes('tool'));await page.locator('[data-quest="tool"]').click();assert.match(await page.locator('#quest-detail').textContent(),/Выполнено/);check('A paid pocket craft performed before opening the book is automatically credited');
 await page.locator('[data-quest="auto"]').evaluate(e=>e.click());assert.equal(await page.locator('.quest-track').count(),0);await click('#quest-close');assert.equal(await page.locator('#objective-text').textContent(),'Дерево развития');await pause();await page.evaluate(()=>window.__vireon.save());const before=(await snapshot()).progress.quests;await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#continue');await page.waitForFunction(()=>window.__vireon.getState().running||window.__vireon.getState().dialog==='lease-panel');if((await state()).dialog==='lease-panel')await click('#lease-primary');await page.waitForFunction(()=>window.__vireon.getState().running);assert.deepEqual((await state()).quests,before);assert.equal(await page.locator('#objective-text').textContent(),'Дерево развития');check('IndexedDB retains completed goals and spent-material evidence; no HUD pinning');
 await pause();await page.evaluate(async()=>{const {makeBuilding,connect,startJob}=await import('/src/game/production.ts');const {addItems}=await import('/src/game/inventory.ts');const s=window.__vireon.snapshot();const bench=makeBuilding(s,'workbench',46,0,45);bench.level=2;const gen=makeBuilding(s,'biogenerator',44,0,45);gen.energy=400000;const kiln=makeBuilding(s,'kiln',50,0,48),electro=makeBuilding(s,'electrolyzer',44,0,48),dome=makeBuilding(s,'dome',49,0,45),dist=makeBuilding(s,'distributor',49,0,45);dome.zone.q=500000;dome.zone.purity=1;dome.zone.temperature=20;for(const [id,n] of [['copper',2],['cable',3],['gas_pipe',1]])addItems(s.player.inventory,id,n);connect(s,'cable',gen.id,bench.id);connect(s,'cable',gen.id,electro.id);connect(s,'cable',bench.id,dist.id);connect(s,'gas_pipe',electro.id,dist.id);s.player.x=46;s.player.z=45;startJob(s,'craft_wire',bench.id);s.player.x=40;s.player.z=42;window.__vireon.setState(s);});
 await click('#resume');await page.waitForFunction(()=>window.__vireon.getState().quests.completed.includes('auto'));await page.waitForFunction(()=>window.__vireon.getState().quests.completed.includes('base'));await page.keyboard.press('j');await page.setViewportSize({width:1366,height:768});await click('#quest-fit');await page.locator('[data-quest="base"]').evaluate(e=>e.click());assert.equal(await page.locator('[data-quest="base"]').getAttribute('data-status'),'done');await shot('base');check('Real powered workbench II output away from player plus currently habitable dome credits automation and the combined milestone');
 await page.locator('[data-quest="air"]').evaluate(e=>e.click());await shot('air');await page.locator('[data-quest="bench2"]').evaluate(e=>e.click());assert.equal(await page.locator('.quest-costs').count(),0);await shot('upgrade');
 const layoutBefore=await page.locator('.quest-node').evaluateAll(es=>es.map(e=>[e.dataset.quest,e.style.left,e.style.top]));await page.locator('[data-quest="power"]').evaluate(e=>e.click());assert.deepEqual(await page.locator('.quest-node').evaluateAll(es=>es.map(e=>[e.dataset.quest,e.style.left,e.style.top])),layoutBefore);await page.keyboard.press('Escape');await shot('overview');check('Selection does not re-layout nodes; compact objectives and completed milestones render');
 for(const size of [{width:844,height:390},{width:667,height:320},{width:568,height:320}]){
  await page.setViewportSize(size);await page.waitForTimeout(350);await page.locator('[data-quest="air"]').evaluate(e=>e.click());await page.waitForTimeout(350);
  const measures=await page.locator('#quest-panel').evaluate(panel=>{const p=panel.getBoundingClientRect();const controls=[...panel.querySelectorAll('button')].filter(b=>getComputedStyle(b).display!=='none'&&b.getClientRects().length);return {panel:[p.left,p.top,p.right,p.bottom],small:controls.filter(b=>{const r=b.getBoundingClientRect();return r.width<31.99||r.height<31.99;}).map(b=>[b.textContent,b.getBoundingClientRect().width,b.getBoundingClientRect().height]),overflow:document.documentElement.scrollWidth>innerWidth,brokenImages:[...panel.querySelectorAll('img')].filter(i=>!i.complete||!i.naturalWidth).length,detailReachable:panel.querySelector('.quest-detail-body').clientHeight>20};});
  report.layout.push({size,...measures});assert.deepEqual(measures.small,[]);assert.equal(measures.overflow,false);assert.equal(measures.brokenImages,0);assert.ok(measures.detailReachable);assert.ok(measures.panel[0]>=0&&measures.panel[1]>=0&&measures.panel[2]<=size.width+1&&measures.panel[3]<=size.height+1);
  const cost=page.locator('.quest-detail-body');await cost.evaluate(e=>e.scrollTop=e.scrollHeight);assert.match(await cost.textContent(),/Нужно всё/);await shot(size.width+'x'+size.height+'-air');await page.keyboard.press('Escape');await click('#quest-fit');assert.ok((await state()).questBook.zoom>=.4);await click('#quest-zoom-in');await page.locator('[data-quest="air"]').evaluate(e=>e.click());await page.locator('.quest-condition').filter({hasText:'Купол'}).click();assert.equal((await state()).questBook.selected,'dome');await page.keyboard.press('Escape');
  check(`${size.width}×${size.height}: map pan/zoom, readable card, popup scrolling and all controls ≥32×32 CSS px`);
 }
 await page.setViewportSize({width:1366,height:768});await click('#quest-close');await pause();await click('#quests-button');await click('#quest-close');assert.equal((await state()).dialog,'paused');check('Pause-menu entry returns to pause instead of unexpectedly resuming simulation');
 assert.deepEqual(report.errors,[]);check('No JavaScript or browser console errors');
}catch(e){report.failure=String(e.stack??e);throw e;}finally{await writeFile('artifacts/s25-quest-verification.json',JSON.stringify(report,null,2));await browser?.close();await server.close();}
