/** Real RAF, actual diagnostic controls/download, bounded craft and shadow projection checks.
 * SwiftShader verifies behavior, not a physical device performance target. */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createServer} from 'vite';
await mkdir('artifacts',{recursive:true});const server=await createServer({server:{host:'127.0.0.1',port:5188,strictPort:true}});await server.listen();let browser;
const report={checks:[],errors:[],environment:'Chromium SwiftShader 844x390, unmodified RAF; GPU is software, not phone FPS'};
const check=name=>{report.checks.push(name);console.log('PASS:',name);};
try{
 let launch={headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']};if(process.env.VIREON_CHROMIUM_PATH)launch.executablePath=process.env.VIREON_CHROMIUM_PATH;
 if(process.env.VIREON_CHROMIUM_MODULE){const c=(await import(process.env.VIREON_CHROMIUM_MODULE)).default;launch={...launch,executablePath:await c.executablePath(),args:[...c.args.filter(x=>!['--disable-web-security','--allow-running-insecure-content'].includes(x)),...launch.args]};}
 browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,acceptDownloads:true});await context.addInitScript(()=>localStorage.setItem('vireon.settings',JSON.stringify({quality:'low',sound:false,bob:false})));
 const page=await context.newPage();page.setDefaultTimeout(90000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});const click=s=>page.locator(s).click(),state=()=>page.evaluate(()=>window.__vireon.getState()),snapshot=()=>page.evaluate(()=>window.__vireon.snapshot());
 const shot=async name=>{await page.waitForTimeout(450);await page.screenshot({path:`artifacts/s27-${name}.png`});};
 await page.goto('http://127.0.0.1:5188');await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#start');await page.waitForFunction(()=>document.body.dataset.running==='true');await click('#pause-button');await click('#settings-button');await click('#diagnostics-button');assert.equal((await state()).dialog,'diagnostics-panel');await click('#diagnostics-toggle');assert.equal((await state()).diagnostics,true);await shot('diagnostics');check('Opt-in diagnostics is available through settings and starts without a save mutation');
 await click('#diagnostics-back');await click('#settings-back');await page.evaluate(async()=>{const {addItems}=await import('/src/game/inventory.ts');const s=window.__vireon.snapshot();addItems(s.player.inventory,'stone',8);addItems(s.player.inventory,'fiber',5);window.__vireon.setState(s);});await click('#resume');await page.keyboard.press('b');await page.locator('[data-recipe="craft_workbench"]').click();const before=await snapshot();await click('.craft-primary');await page.waitForFunction(()=>!window.__vireon.snapshot().world.base.hand);const after=await snapshot();assert.ok(after.meta.activeTicks>before.meta.activeTicks);assert.ok(after.player.inventory.some(s=>s?.itemId==='workbench'));assert.equal(after.player.inventory.reduce((n,s)=>n+(s?.itemId==='stone'?s.count:0),0),0);await shot('craft-recording');check('Live craft advances the same simulation, pays eight stone once and completes while diagnostics records');
 await click('#close-production');await click('#pause-button');await page.evaluate(()=>window.__vireon.teleport(43,52,.08,-.55));await page.waitForTimeout(600);const first=(await state()).shadowTarget;await page.evaluate(()=>window.__vireon.teleport(43,52,1.2,.2));await page.waitForTimeout(600);assert.deepEqual((await state()).shadowTarget,first);check('Turning the camera at the same paused ground position does not move the shadow projection');
 for(const quality of ['low','standard','high']){
  await click('#settings-button');while((await state()).quality!==quality)await click('#quality-toggle');await click('#settings-back');await click('#resume');await page.evaluate(()=>window.__vireon.teleport(43,52,.08,-.55));await shot('grass-'+quality);await page.evaluate(()=>window.__vireon.teleport(66.3,61.8,.05,-.40));await shot('ore-'+quality);report[quality+'Geometry']=(await page.evaluate(()=>window.__vireon.diagnostics())).metadata.sceneGeometry;await click('#pause-button');await page.waitForTimeout(600);const stableA=await page.evaluate(()=>window.__vireon.captureFrame());await page.waitForTimeout(350);const stableB=await page.evaluate(()=>window.__vireon.captureFrame());assert.equal(stableB===stableA,true,'Paused raw 3D pixels must stay stable in '+quality);
 }
 check('Grass and ground-contact ores render in all presets; paused 3D pixels stay identical between frames');
 await click('#settings-button');await click('#diagnostics-button');await page.setViewportSize({width:568,height:320});await shot('diagnostics-compact');const small=await page.locator('#diagnostics-panel button:visible').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width<32||e.getBoundingClientRect().height<32).map(e=>e.id));assert.deepEqual(small,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);check('Diagnostic controls fit 568x320 and retain 32px touch targets');
 await click('#diagnostics-toggle');assert.equal((await state()).diagnostics,false);const [download]=await Promise.all([page.waitForEvent('download'),click('#diagnostics-export')]);await download.saveAs('artifacts/s27-device-log.json');const log=JSON.parse(await readFile('artifacts/s27-device-log.json','utf8'));assert.equal(log.format,'vireon-performance');assert.ok(log.summary.frames>0);assert.ok(log.stages['production:draw'].count>0);assert.ok(log.stages['save:encode'].count>0);assert.ok(log.events.some(e=>e.name==='input:click'));assert.ok(log.samples.some(e=>e.context.dialog==='production-panel'));assert.ok(log.samples.length<=600&&log.spikes.length<=240&&log.events.length<=240);assert.equal(JSON.stringify(log).includes('inventory'),false);report.summary=log.summary;report.stages=log.stages;check('Actual JSON download contains bounded frame, crafting, save, input and quality data without world inventory');
 const stable=await page.evaluate(()=>window.__vireon.diagnostics().summary.frames);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.__vireon.diagnostics().summary.frames),stable);await click('#diagnostics-clear');assert.equal(await page.evaluate(()=>window.__vireon.diagnostics().summary.frames),0);check('Stop freezes the recording; Clear removes its data');
 assert.deepEqual(report.errors,[]);check('No runtime or shader errors');
}catch(e){report.failure=String(e.stack??e);throw e;}finally{await writeFile('artifacts/s27-verification.json',JSON.stringify(report,null,2));await browser?.close();await server.close();}
