/** Real S2.3 controls and IndexedDB, bounded materials; no human timing/FPS claim. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createServer} from 'vite';
await mkdir('artifacts',{recursive:true});const server=await createServer({server:{host:'127.0.0.1',port:5181,strictPort:true}});await server.listen();let browser;
const report={checks:[],errors:[],environment:'Chromium / SwiftShader; bounded stock fixtures, actual controls and IndexedDB'};
const check=text=>{report.checks.push(text);console.log('PASS:',text);};
try{
 let launch={headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']};
 if(process.env.VIREON_CHROMIUM_PATH)launch.executablePath=process.env.VIREON_CHROMIUM_PATH;
 if(process.env.VIREON_CHROMIUM_MODULE){const c=(await import(process.env.VIREON_CHROMIUM_MODULE)).default;launch={...launch,executablePath:await c.executablePath(),args:[...c.args.filter(x=>!['--disable-web-security','--allow-running-insecure-content'].includes(x)),...launch.args]};}
 browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true});await context.addInitScript(()=>{localStorage.setItem('vireon.settings',JSON.stringify({quality:'low',sound:false}));const raf=window.requestAnimationFrame.bind(window);window.requestAnimationFrame=fn=>raf(t=>setTimeout(()=>fn(t),120));});
 const page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 const click=s=>page.$eval(s,e=>e.click()),snapshot=()=>page.evaluate(()=>window.__vireon.snapshot());
 const pause=async()=>{await click('#pause-button');await page.evaluate(()=>window.__vireon.save());};
 const select=async id=>{const n=await page.evaluate(()=>window.__vireon.getState().activeTicks);await page.waitForFunction(n=>window.__vireon.getState().activeTicks>n,n);await click('#craft-button');await page.locator('#production-content>select').selectOption(id);};
 const choose=async id=>click(`[data-recipe="${id}"]`);
 const count=(s,id)=>s.player.inventory.reduce((n,v)=>n+(v?.itemId===id?v.count:0),0);
 const buttons=async()=>{await page.waitForTimeout(350);const small=await page.locator('#production-panel button:visible').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width<31.99||r.height<31.99;}).map(e=>({label:e.textContent,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));assert.deepEqual(small,[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));};
 await page.goto('http://127.0.0.1:5181');await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#start');await page.waitForFunction(()=>window.__vireon.getState().running);
 await pause();await page.evaluate(async()=>{const {addItems}=await import('/src/game/inventory.ts');const s=window.__vireon.snapshot();for(const [id,n] of [['stone',8],['fiber',5],['iron',10],['copper',4],['wire',4],['circuit',1],['cable',1]])addItems(s.player.inventory,id,n);window.__vireon.setState(s);});await click('#resume');
 await select('hand');assert.equal(await page.locator('.craft-inputs .craft-cell').count(),2);assert.equal(await page.locator('.craft-inventory-cell').count(),24);assert.equal(await page.locator('#production-panel').getByRole('button',{name:'В очередь',exact:true}).count(),0);const before=await snapshot();await page.locator('#craft-search').focus();await page.keyboard.type('micb');assert.equal(await page.evaluate(()=>window.__vireon.getState().dialog),'production-panel');assert.equal(await page.locator('#craft-search').inputValue(),'micb');await page.locator('#craft-search').fill('ключ');assert.equal(await page.locator('.craft-recipe-grid button').count(),1);await page.locator('#craft-search').fill('');await page.locator('.craft-categories').getByRole('button',{name:'Снар.',exact:true}).click();assert.equal(await page.locator('.craft-recipe-grid button').count(),3);await page.locator('.craft-categories').getByRole('button',{name:'Все',exact:true}).click();await page.locator('.craft-inventory-cell').filter({has:page.locator('[data-item="copper"]')}).click();assert.equal(await page.locator('[data-recipe="grass_parts"]').count(),0);await click('.craft-material-filter');await click('.craft-filter');assert.equal(await page.locator('.craft-recipe-grid button').count(),2);await click('.craft-filter');assert.deepEqual((await snapshot()).player.inventory,before.player.inventory);check('Catalogue search, category, ingredient and availability filters preserve materials');await choose('craft_wrench');assert.deepEqual((await snapshot()).player.inventory,before.player.inventory);assert.equal(await page.locator('#production-panel').getByRole('button',{name:'Нужна станция',exact:true}).isDisabled(),true);await choose('craft_workbench');await buttons();await page.screenshot({path:'artifacts/s23-pocket.png'});await page.locator('#production-panel').getByRole('button',{name:'Создать',exact:true}).click();await page.waitForFunction(()=>!window.__vireon.getState().base.hand);assert.equal(count(await snapshot(),'workbench'),1);check('Pocket has two inputs / 24 backpack slots, locked station recipes, one paid craft and no queue');
 await click('#production-build');for(const [axis,n] of [['x','46'],['z','45']]){await page.locator('#build-'+axis).fill(n);await page.locator('#build-'+axis).dispatchEvent('change');}await page.locator('#production-panel').getByRole('button',{name:'Разместить',exact:true}).click();const bench=(await snapshot()).world.base.buildings[0].id;await click('#close-production');await page.evaluate(()=>window.__vireon.teleport(45,45,0,-.1));await select(bench);await choose('craft_wrench');assert.equal(await page.locator('.craft-inputs .craft-cell').count(),4);assert.equal(await page.locator('.craft-quantity').count(),0);await page.locator('#production-panel').getByRole('button',{name:'Дополнить',exact:true}).click();await buttons();await page.screenshot({path:'artifacts/s23-workbench-I.png'});await page.locator('#production-panel').getByRole('button',{name:'Создать',exact:true}).click();await page.waitForFunction(id=>window.__vireon.getState().base.buildings.find(b=>b.id===id).job.workMs>=1000,bench);await click('#close-production');await page.evaluate(()=>window.__vireon.teleport(40,42,0,0));const wip=(await snapshot()).world.base.buildings[0].job.workMs,ticks=(await snapshot()).meta.activeTicks;await page.waitForFunction(n=>window.__vireon.getState().activeTicks>n+25,ticks);assert.equal((await snapshot()).world.base.buildings[0].job.workMs,wip);check('Workbench I uses four buffered inputs and pauses when the player leaves');
 await page.evaluate(()=>window.__vireon.teleport(45,45,0,-.1));await select(bench);await page.locator('#craft-search').fill('провод');await page.locator('#craft-search').focus();await page.waitForFunction(id=>!window.__vireon.getState().base.buildings.find(b=>b.id===id).job,bench);assert.equal(await page.evaluate(()=>document.activeElement.id),'craft-search');assert.equal(await page.locator('#craft-search').inputValue(),'провод');await page.locator('#craft-search').fill('');await page.locator('#production-panel').getByRole('button',{name:'Забрать',exact:true}).click();assert.equal(count(await snapshot(),'wrench'),1);await page.locator('.craft-inventory-cell').filter({has:page.locator('[data-item="wrench"]')}).click();await click('#close-production');await page.waitForFunction(()=>window.__vireon.getState().action==='upgrade');assert.equal((await page.evaluate(()=>window.__vireon.getState())).handItem,true);await page.keyboard.press('KeyF');assert.equal(await page.locator('.craft-layout[data-mode="upgrade"]').count(),1);await page.screenshot({path:'artifacts/s23-upgrade.png'});await page.locator('#production-panel').getByRole('button',{name:'Улучшить',exact:true}).click();assert.equal((await snapshot()).world.base.buildings[0].level,2);assert.equal(count(await snapshot(),'wrench'),1);assert.equal(count(await snapshot(),'iron'),0);assert.equal(count(await snapshot(),'wire'),0);assert.equal(count(await snapshot(),'circuit'),0);check('Crafted wrench equips in the hotbar and world F opens the paid upgrade; tool is retained');
 await page.locator('#production-panel').getByRole('button',{name:'К сборке',exact:true}).click();await choose('craft_wire');await page.locator('#production-panel').getByRole('button',{name:'+',exact:true}).click();await page.locator('#production-panel').getByRole('button',{name:'В очередь',exact:true}).click();await page.waitForFunction(id=>!!window.__vireon.getState().base.buildings.find(b=>b.id===id).job,bench);assert.match(await page.locator('#production-status').textContent(),/нет питания/);assert.equal((await snapshot()).world.base.buildings[0].job.workMs,0);await buttons();await page.screenshot({path:'artifacts/s23-workbench-II.png'});await click('#close-production');
 await pause();await page.evaluate(async()=>{const {makeBuilding}=await import('/src/game/production.ts');const s=window.__vireon.snapshot();makeBuilding(s,'biogenerator',44,s.world.base.buildings[0].y,45);window.__vireon.setState(s);});await click('#resume');const gen=(await snapshot()).world.base.buildings[1].id;await select(gen);await page.locator('#production-panel').getByRole('button',{name:'Загрузить 1 волокно',exact:true}).click();await click('#production-links');await page.locator('#link-kind').selectOption('cable');await page.locator('#link-from').selectOption(gen);await page.locator('#link-to').selectOption(bench);await page.locator('#production-panel').getByRole('button',{name:'Соединить',exact:true}).click();assert.equal(count(await snapshot(),'cable'),0);await click('#close-production');await page.evaluate(()=>window.__vireon.teleport(40,42,0,0));await page.waitForFunction(id=>window.__vireon.getState().base.buildings.find(b=>b.id===id).job?.workMs>1000,bench);
 await pause();const saved=await snapshot();await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#continue');await page.waitForFunction(()=>window.__vireon.getState().running||window.__vireon.getState().dialog==='lease-panel');if((await page.evaluate(()=>window.__vireon.getState())).dialog==='lease-panel')await click('#lease-primary');await page.waitForFunction(()=>window.__vireon.getState().running);assert.equal((await snapshot()).world.base.buildings[0].level,2);assert.ok((await snapshot()).world.base.buildings[0].job.workMs>=saved.world.base.buildings[0].job.workMs);await page.waitForFunction(id=>{const b=window.__vireon.getState().base.buildings.find(b=>b.id===id);return !b.job&&!b.queue.length;},bench);const done=await snapshot();assert.equal(done.world.base.buildings[0].output.reduce((n,s)=>n+(s?.itemId==='wire'?s.count:0),0),8);assert.equal(done.world.base.buildings[1].energy+done.world.base.buildings[1].fuel,136000);check('Workbench II completes two paid batches away after actual reload and uses exactly 64 EU from one fiber');
 await page.evaluate(()=>window.__vireon.teleport(45,45,0,-.1));await select(bench);await page.setViewportSize({width:667,height:320});await buttons();assert.equal(await page.locator('.craft-inventory-cell').count(),24);await page.screenshot({path:'artifacts/s23-compact-auto.png'});await page.locator('#production-content>select').selectOption('hand');await buttons();await page.screenshot({path:'artifacts/s23-compact-pocket.png'});check('Pocket and automated workbench fit 667×320 with all buttons at least 32×32 CSS pixels');
 assert.deepEqual(report.errors,[]);check('No runtime / console errors in the crafting progression');
}catch(e){report.failure=e.stack;throw e;}finally{await writeFile('artifacts/s23-crafting-verification.json',JSON.stringify(report,null,2)+'\n');await browser?.close();await server.close();}
