/** S2.6 real controls, finite stock, IndexedDB and landscape screenshots. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createServer} from 'vite';
await mkdir('artifacts',{recursive:true});const server=await createServer({server:{host:'127.0.0.1',port:5178,strictPort:true}});await server.listen();let browser;
const report={checks:[],errors:[],layout:[],environment:'Chromium / SwiftShader; bounded stock, real controls and IndexedDB; not phone FPS'};
const check=t=>{report.checks.push(t);console.log('PASS:',t);};
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.VIREON_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true});await context.addInitScript(()=>{localStorage.setItem('vireon.settings',JSON.stringify({quality:'low',sound:false}));const raf=requestAnimationFrame.bind(window);window.requestAnimationFrame=fn=>raf(t=>setTimeout(()=>fn(t),120));});
 const page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 const click=s=>page.$eval(s,e=>e.click()),state=()=>page.evaluate(()=>window.__vireon.getState()),snapshot=()=>page.evaluate(()=>window.__vireon.snapshot());
 const shot=async name=>{await page.locator('img:visible').evaluateAll(es=>Promise.all(es.map(e=>e.decode())));await page.waitForFunction(()=>[...document.querySelectorAll('.panel,.title-block')].filter(p=>p.getClientRects().length).every(p=>Number(getComputedStyle(p).opacity)>.99));await page.waitForTimeout(1000);await page.screenshot({path:`artifacts/s26-${name}.png`});};
 const pause=async()=>{if((await state()).dialog==='production-panel')await click('#close-production');if((await state()).running)await click('#pause-button');};
 const configure=async fn=>{await pause();await page.evaluate(fn);await click('#resume');};
 const face=async id=>{await page.evaluate(async id=>{const {heightAt}=await import('/src/world.ts');const s=window.__vireon.snapshot(),b=s.world.base.buildings.find(b=>b.id===id)??(id==='crate-a'?{x:44.8,y:heightAt(44.8,41.4),z:41.4}:null);if(!b)throw Error('Missing target '+id);const x=b.x,z=b.z+2.4,pitch=Math.atan2(b.y+.7-heightAt(x,z)-1.8,2.4);window.__vireon.teleport(x,z,Math.PI,pitch);},id);await page.waitForFunction(id=>window.__vireon.getState().worldTarget===id,id);};
 const open=async id=>{if((await state()).dialog==='production-panel')await click('#close-production');await face(id);await page.keyboard.press('f');await page.waitForFunction(()=>window.__vireon.getState().dialog==='production-panel');};
 const inventory=async id=>{const cells=await snapshot();const i=cells.player.inventory.findIndex(s=>s?.itemId===id);assert.ok(i>=0,'Missing inventory '+id);await page.locator('.machine-backpack .machine-cell').nth(i).click();};
 const validate=async name=>{await page.waitForTimeout(350);const data=await page.locator('#production-panel').evaluate(p=>{const r=p.getBoundingClientRect();return {rect:[r.left,r.top,r.right,r.bottom],small:[...p.querySelectorAll('button')].filter(b=>b.getClientRects().length&&getComputedStyle(b).display!=='none').filter(b=>{const r=b.getBoundingClientRect();return r.width<31.99||r.height<31.99;}).map(b=>b.textContent),overflow:document.documentElement.scrollWidth>innerWidth};});report.layout.push({name,...data});assert.deepEqual(data.small,[]);assert.equal(data.overflow,false);};
 await page.goto('http://127.0.0.1:5178');await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('.title-foot').count(),0);await shot('title');await click('#start');await page.waitForFunction(()=>window.__vireon.getState().running);assert.equal(await page.locator('#suit-button').count(),0);assert.equal(await page.locator('#hud-buttons button').count(),4);check('Title caption removed; four HUD menu buttons; suit remains available with C');
 await configure(async()=>{const s=window.__vireon.snapshot();s.player.x=55;s.player.z=42;s.player.y=0;s.player.yaw=0;window.__vireon.setState(s);});
 await page.locator('#joystick').evaluate(e=>{const r=e.getBoundingClientRect();e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true,pointerId:11,pointerType:'touch',clientX:r.x+r.width/2,clientY:r.y+10}));});await page.locator('#run').dispatchEvent('pointerdown',{pointerId:12,pointerType:'touch',bubbles:true,cancelable:true});await page.waitForFunction(()=>window.__vireon.getState().input.run&&window.__vireon.getState().input.forward>0);await page.keyboard.press('Space');await page.waitForFunction(()=>!window.__vireon.getState().grounded);await page.locator('#joystick').dispatchEvent('pointerup',{pointerId:11,pointerType:'touch'});check('Walking joystick and second touch can enable run; jump works during the same motion');
 await configure(async()=>{const {addItems}=await import('/src/game/inventory.ts');const s=window.__vireon.snapshot();addItems(s.player.inventory,'stone',7);s.world.nodes['iron-a']=0;s.world.nodes['copper-a']=0;window.__vireon.setState(s);window.__vireon.teleport(30,54.5,Math.PI,-.5);});await page.waitForFunction(()=>window.__vireon.getState().action==='mine'&&document.getElementById('aim-meta').textContent.includes('В рюкзаке: 7'));assert.match(await page.locator('#aim-meta').textContent(),/В рюкзаке: 7/);await page.keyboard.down('f');await page.waitForFunction(()=>window.__vireon.getState().cells.some(s=>s?.itemId==='stone'&&s.count>=8));await page.keyboard.up('f');await shot('mining');await page.evaluate(()=>window.__vireon.teleport(110,20,-Math.PI/2,0));await page.waitForFunction(()=>document.getElementById('aim').hidden);const collisions=await page.evaluate(async()=>{const {boxes}=await import('/src/world.ts');return boxes.filter(b=>['iron-outcrop','copper-outcrop'].includes(b.id)).length;});assert.equal(collisions,0);check('Mining reports backpack count, empty aim strip hides; depleted main ores have no collider while secondary deposits remain');
 await configure(async()=>{const s=window.__vireon.snapshot();s.player.inventory[12]={itemId:'workbench',count:1};s.player.hotbar=2;window.__vireon.setState(s);window.__vireon.teleport(46,48,Math.PI,-.65);});await page.keyboard.press('i');await page.locator('#inventory-grid [data-cell="12"]').click();assert.equal(await page.locator('#craft-button').textContent(),'Крафт');await page.waitForFunction(()=>getComputedStyle(document.getElementById('inventory-panel')).transform==='none');assert.ok(await page.locator('#inv-detail .d-actions button').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth+1&&e.getBoundingClientRect().height>=32)));await shot('inventory-build');await page.locator('#act-world').click();await page.waitForFunction(()=>window.__vireon.getState().action==='place');const activeBody=(await snapshot()).player.hotbar;assert.equal((await snapshot()).player.inventory[12],null);await shot('placement');await page.keyboard.press('f');await page.waitForFunction(()=>window.__vireon.getState().base.buildings.length===1);const placed=(await snapshot()).world.base.buildings[0].id;assert.equal((await snapshot()).player.inventory[activeBody],null);await face(placed);await page.waitForFunction(()=>!document.getElementById('retrieve-station').hidden);await page.keyboard.press('r');assert.equal((await snapshot()).world.base.buildings.length,0);assert.ok((await snapshot()).player.inventory.some(s=>s?.packed));check('Aim placement spends one real body; R picks up a stateful station instead of deleting it');
 await configure(async()=>{const {makeBuilding}=await import('/src/game/production.ts');const {heightAt}=await import('/src/world.ts');const {addItems}=await import('/src/game/inventory.ts');const s=window.__vireon.snapshot();s.player.inventory=s.player.inventory.map(v=>v?.packed?null:v);for(const [id,n] of [['iron_raw',1],['fiber',8],['ice',1],['cable',2],['gas_pipe',1]])addItems(s.player.inventory,id,n);for(const [kind,x,z] of [['kiln',48,48],['biogenerator',44,45],['electrolyzer',46,45],['refill',46,42]])makeBuilding(s,kind,x,heightAt(x,z)+.12,z);const reserve=Math.min(240000,s.world.capsuleMilliGU);s.world.capsuleMilliGU-=reserve;s.player.bottles[1]={itemId:'bottle_1',count:1,milliGU:reserve};s.player.hotbar=0;window.__vireon.setState(s);});let base=(await snapshot()).world.base;const kiln=base.buildings.find(b=>b.kind==='kiln').id,gen=base.buildings.find(b=>b.kind==='biogenerator').id,electro=base.buildings.find(b=>b.kind==='electrolyzer').id,refill=base.buildings.find(b=>b.kind==='refill').id;
 await open(kiln);assert.equal(await page.locator('[data-machine-slot]').count(),3);assert.equal(await page.locator('.recipe-list').count(),0);await inventory('iron_raw');await inventory('fiber');await page.waitForFunction(id=>window.__vireon.getState().base.buildings.find(b=>b.id===id).output[0]?.itemId==='iron',kiln);await page.locator('[data-machine-slot="Результат"]').click();await inventory('ice');await page.waitForFunction(id=>window.__vireon.getState().base.buildings.find(b=>b.id===id).output[0]?.itemId==='water',kiln);await validate('kiln844');await shot('kiln');await page.locator('[data-machine-slot="Результат"]').click();await page.locator('[data-machine-slot="Топливо"]').click();check('Furnace has three slots, processes ore and ice with paid fuel, yields portable water and actual output');
 await click('#close-production');await configure(async()=>{const s=window.__vireon.snapshot();const i=s.player.inventory.findIndex(s=>s?.itemId==='cable');const old=s.player.inventory[3];s.player.inventory[3]=s.player.inventory[i];s.player.inventory[i]=old;s.player.hotbar=3;window.__vireon.setState(s);});await face(gen);await page.keyboard.press('f');await page.waitForFunction(()=>document.getElementById('aim-meta').textContent.includes('второй порт'));await face(electro);await shot('cable-preview');await page.keyboard.press('f');await page.waitForFunction(()=>window.__vireon.getState().base.links.length===1);assert.equal((await snapshot()).world.base.links[0].kind,'cable');check('Two world ports create a paid cable, with a visible preview between selections');
 await configure(async()=>{const s=window.__vireon.snapshot();const i=s.player.inventory.findIndex(s=>s?.itemId==='gas_pipe');const old=s.player.inventory[3];s.player.inventory[3]=s.player.inventory[i];s.player.inventory[i]=old;s.player.hotbar=3;window.__vireon.setState(s);});await page.keyboard.press('i');const pipeIndex=(await snapshot()).player.inventory.findIndex(s=>s?.itemId==='gas_pipe');await page.locator('#inventory-grid [data-cell="'+pipeIndex+'"]').click();assert.equal(await page.locator('#act-world span').textContent(),'Соединить');await page.locator('#act-world').click();await page.waitForFunction(()=>window.__vireon.getState().action==='link');await face(refill);await page.keyboard.press('f');await face(electro);await page.keyboard.press('f');await page.waitForFunction(()=>window.__vireon.getState().base.links.length===2);assert.equal((await snapshot()).world.base.links.find(l=>l.kind==='gas_pipe').from,electro);check('Manual pipe connection infers oxygen direction even when the consumer is selected first');
 await configure(async()=>{const s=window.__vireon.snapshot();s.player.hotbar=0;window.__vireon.setState(s);});await open(gen);await inventory('fiber');await open(electro);await inventory('water');const mountedBefore=(await snapshot()).player.bottles[0].milliGU;await page.locator('.machine-process button').filter({hasText:'Установить баллон 1'}).click();await page.waitForFunction(({id,before})=>(window.__vireon.getState().base.buildings.find(b=>b.id===id).input[1]?.milliGU??0)>before,{id:electro,before:mountedBefore});assert.equal(await page.locator('[data-machine-slot]').count(),2);assert.equal(await page.locator('.machine-bar').count(),1);await validate('oxygen844');await shot('oxygen');await page.locator('[data-machine-slot="Баллон"]').click();assert.ok((await snapshot()).player.inventory.some(s=>s?.itemId==='bottle_1'&&s.milliGU>0));check('Two-slot oxygen generator fills a mounted real bottle from its single visible internal buffer with paid power');
 await open('crate-a');await inventory('bottle_1');assert.ok((await snapshot()).world.crates['crate-a'].some(s=>s?.itemId==='bottle_1'&&s.milliGU>0));await validate('crate844');await shot('crate');check('Starting crate accepts actual items, including tank gas');
 for(const size of [{width:667,height:320},{width:568,height:320}]){await page.setViewportSize(size);await validate('crate'+size.width);await shot('crate-'+size.width);await open(electro);await validate('oxygen'+size.width);await shot('oxygen-'+size.width);await open(kiln);await validate('kiln'+size.width);await shot('kiln-'+size.width);await open('crate-a');}
 check('Furnace, oxygen and storage layouts fit 844×390, 667×320 and 568×320; all controls ≥32×32');
 await click('#close-production');await page.setViewportSize({width:844,height:390});await configure(async()=>{const s=window.__vireon.snapshot();s.player.bottles[0]={itemId:'bottle_1',count:1,milliGU:120000};window.__vireon.setState(s);window.__vireon.teleport(40,42,0,0);});await page.waitForFunction(()=>window.__vireon.getState().action==='capsule');await page.keyboard.press('f');await page.locator('#capsule-start').click();await page.waitForFunction(()=>window.__vireon.getState().bottles[0].milliGU>125000);await shot('capsule');await page.locator('.machine-process button').filter({hasText:'Остановить'}).click();const stopped=(await snapshot()).player.bottles[0].milliGU;await page.waitForTimeout(600);assert.equal((await snapshot()).player.bottles[0].milliGU,stopped);await click('#close-production');check('Capsule click starts refill with explicit direction; Stop halts transfer without reversing automatically');
 await page.setViewportSize({width:844,height:390});await page.keyboard.press('j');await page.locator('#quest-panel').waitFor({state:'visible'});assert.equal((await state()).dialog,'quest-panel');await click('#quest-fit');await page.locator('[data-quest="air"]').click();assert.equal(await page.locator('.quest-track,.quest-costs').count(),0);const popup=await page.locator('#quest-detail').boundingBox();assert.ok(popup.width<=300&&popup.height<=190);await shot('quest-popup');await click('#quest-close');check('Quest selection opens a compact bounded popup without resource costs or HUD pinning');
 await pause();await page.evaluate(()=>window.__vireon.save());const before=await snapshot();await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#continue');await page.waitForFunction(()=>window.__vireon.getState().running||window.__vireon.getState().dialog==='lease-panel');if((await state()).dialog==='lease-panel')await click('#lease-primary');await page.waitForFunction(()=>window.__vireon.getState().running);const after=await snapshot();assert.deepEqual(after.world.crates,before.world.crates);assert.equal(after.world.base.links.length,before.world.base.links.length);assert.equal(after.meta.stateVersion,6);check('Actual IndexedDB reload preserves crate item state, stations and manual links in schema v6');
 assert.deepEqual(report.errors,[]);check('No runtime or browser console errors');
}catch(e){report.failure=String(e.stack??e);throw e;}finally{await writeFile('artifacts/s26-verification.json',JSON.stringify(report,null,2));await browser?.close();await server.close();}
