/** S2.2: real controls → crafting / ports / airlock → persistence. Bounded fixtures; not V01 timing. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createServer} from 'vite';
await mkdir('artifacts',{recursive:true});const server=await createServer({server:{host:'127.0.0.1',port:5178,strictPort:true}});await server.listen();
const report={checks:[],errors:[],environment:'Chromium / SwiftShader, bounded production fixtures; correctness, not phone FPS or full V01.'};const check=s=>{report.checks.push(s);console.log('PASS:',s);};let browser;
try{
 let launch={headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']};
 if(process.env.VIREON_CHROMIUM_PATH)launch.executablePath=process.env.VIREON_CHROMIUM_PATH;
 if(process.env.VIREON_CHROMIUM_MODULE){const c=(await import(process.env.VIREON_CHROMIUM_MODULE)).default;launch={...launch,executablePath:await c.executablePath(),args:[...c.args.filter(x=>!['--disable-web-security','--allow-running-insecure-content'].includes(x)),...launch.args]};}
 browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true});await context.addInitScript(()=>{localStorage.setItem('vireon.settings',JSON.stringify({quality:'low',sound:false}));const raf=window.requestAnimationFrame.bind(window);window.requestAnimationFrame=fn=>raf(t=>setTimeout(()=>fn(t),120));});
 const page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 const click=s=>page.$eval(s,e=>e.click()),state=()=>page.evaluate(()=>window.__vireon.getState()),snapshot=()=>page.evaluate(()=>window.__vireon.snapshot());
 const pause=async()=>{await click('#pause-button');await page.evaluate(()=>window.__vireon.save());};
 const reopen=async()=>{await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#continue');await page.waitForFunction(()=>window.__vireon.getState().running||window.__vireon.getState().dialog==='lease-panel');if((await state()).dialog==='lease-panel')await click('#lease-primary');await page.waitForFunction(()=>window.__vireon.getState().running);};
 const configure=async fn=>{await pause();await page.evaluate(fn);await click('#resume');};
 const selectStation=async id=>{await page.keyboard.press('KeyB');const options=await page.locator('#production-content>select option').evaluateAll(es=>es.map(e=>e.value));assert.ok(options.includes(id),`Station ${id} not within reach; available ${options.join(',')}`);await page.locator('#production-content>select').selectOption(id);};
 const recipe=async id=>click(`[data-recipe="${id}"] button`);
 const connect=async (kind,from,to)=>{await click('#production-links');await page.locator('#link-kind').selectOption(kind);await page.locator('#link-from').selectOption(from);await page.locator('#link-to').selectOption(to);await page.getByRole('button',{name:'Соединить',exact:true}).click();};
 await page.goto('http://127.0.0.1:5178');await page.waitForFunction(()=>document.body.dataset.ready==='true');await click('#start');await page.waitForFunction(()=>window.__vireon.getState().running);assert.equal((await state()).version,'S2.2');
 let dome;
 if(!process.env.VIREON_PRODUCTION_LAYOUT_ONLY){
 await page.evaluate(()=>{const s=window.__vireon.snapshot();s.player.hotbar=1;window.__vireon.setState(s);window.__vireon.teleport(52,63.8,0,-.2);});await page.waitForFunction(()=>window.__vireon.getState().aimNode==='grass-a');const durability=(await snapshot()).player.inventory[0].durability;await page.keyboard.down('KeyF');await page.waitForFunction(()=>window.__vireon.getState().inventory.some(i=>i.itemId==='grass'));await page.keyboard.up('KeyF');assert.equal((await snapshot()).player.inventory[0].durability,durability);check('Grass is actually harvestable by hand and does not wear the tool');
 await configure(()=>{const s=window.__vireon.snapshot();s.player.x=40;s.player.z=42;s.player.inventory[3]={itemId:'stone',count:8};s.player.inventory[4]={itemId:'fiber',count:2};window.__vireon.setState(s);});
 await page.keyboard.press('KeyB');await page.evaluate(()=>{document.querySelector('[data-recipe="grass_parts"] button').click();document.getElementById('pause-button').click();});await page.evaluate(()=>window.__vireon.save());const saved=await snapshot();assert.equal(saved.world.base.hand.recipeId,'grass_parts');assert.equal(saved.world.base.hand.reserved[0].itemId,'grass');await reopen();await page.waitForFunction(()=>!window.__vireon.getState().base.hand);assert.equal((await snapshot()).player.inventory.filter(s=>s?.itemId==='fiber').reduce((n,s)=>n+s.count,0),4);check('Hand WIP reserves real input, survives save/reload and produces exactly once');
 await page.keyboard.press('KeyB');await recipe('craft_workbench');await page.waitForFunction(()=>!window.__vireon.getState().base.hand);await click('#production-build');await page.locator('#build-x').fill('46');await page.locator('#build-x').dispatchEvent('change');await page.locator('#build-z').fill('45');await page.locator('#build-z').dispatchEvent('change');await page.getByRole('button',{name:'Разместить',exact:true}).click();const placed=(await snapshot()).world.base.buildings[0];assert.equal(placed.kind,'workbench');assert.equal(placed.x,46);assert.equal(placed.energy+placed.oxygen+placed.water+placed.fuel,0);assert.equal((await snapshot()).player.inventory.some(s=>s?.itemId==='workbench'),false);check('Build panel spends a crafted body, respects grid coordinates and places it empty');
 await page.screenshot({path:'artifacts/s2-building.png'});await click('#close-production');
 await configure(async()=>{const {makeBuilding}=await import('/src/game/production.ts');const {addItems}=await import('/src/game/inventory.ts');const s=window.__vireon.snapshot();makeBuilding(s,'biogenerator',44,.62,38);makeBuilding(s,'electrolyzer',44,.62,40);makeBuilding(s,'refill',44,.62,36);makeBuilding(s,'dome',48,.62,40);makeBuilding(s,'distributor',47,.62,40);for(const [id,n] of [['fiber',5],['ice',2],['cable',3],['gas_pipe',2]])addItems(s.player.inventory,id,n);s.player.x=45;s.player.z=40;s.player.y=.62;window.__vireon.setState(s);});
 const getId=async kind=>(await snapshot()).world.base.buildings.find(b=>b.kind===kind).id;const gen=await getId('biogenerator'),e=await getId('electrolyzer'),r=await getId('refill'),d=await getId('distributor');dome=await getId('dome');
 await selectStation(e);await recipe('melt_in_generator');const noPower=(await snapshot()).meta.activeTicks;await page.waitForFunction(n=>window.__vireon.getState().activeTicks>n+20,noPower);assert.equal((await snapshot()).world.base.buildings.find(b=>b.id===e).job.workMs,0);check('Melting stalls without a real cable and power supply');
 await connect('cable',gen,e);await click('#production-recipes');await page.locator('#production-content>select').selectOption(gen);for(let i=0;i<3;i++)await page.getByRole('button',{name:'Загрузить 1 волокно',exact:true}).click();await page.locator('#production-content>select').selectOption(e);await page.waitForFunction(id=>window.__vireon.getState().base.buildings.find(b=>b.id===id).water===1000,e);check('A paid cable plus finite fiber fuel powers 1 ice → 1 WU');
 await recipe('electrolysis');await page.waitForFunction(id=>window.__vireon.getState().base.buildings.find(b=>b.id===id).job.workMs>=1000,e);await pause();const wip=(await snapshot()).world.base.buildings.find(b=>b.id===e).job;await reopen();const restored=(await snapshot()).world.base.buildings.find(b=>b.id===e).job;assert.ok(restored.workMs>=wip.workMs&&restored.workMs<wip.workMs+1000);await page.waitForFunction(id=>window.__vireon.getState().base.buildings.find(b=>b.id===id).oxygen===240000,e);assert.equal((await snapshot()).world.base.buildings.find(b=>b.id===e).water,0);check('Powered electrolysis survives reload and yields exactly 240 GU per paid WU');
 await selectStation(e);await connect('cable',gen,r);await connect('gas_pipe',e,r);await click('#close-production');
 await configure(()=>{const s=window.__vireon.snapshot();s.player.x=45;s.player.z=36;s.player.y=.62;s.player.bottles=[{itemId:'bottle_1',count:1,milliGU:2000},{itemId:'bottle_1',count:1,milliGU:230000}];window.__vireon.setState(s);});await selectStation(r);const before=await snapshot();await page.locator('#production-refill').focus();await page.keyboard.down('Space');await page.waitForFunction(()=>window.__vireon.getState().bottles[0].milliGU>22000);await page.keyboard.up('Space');await pause();const after=await snapshot();const gas=s=>s.world.capsuleMilliGU+s.player.bottles.reduce((n,b)=>n+(b?.milliGU??0),0)+s.world.base.buildings.reduce((n,b)=>n+b.oxygen+b.zone.q,0);assert.equal(gas(before)-gas(after),(after.meta.activeTicks-before.meta.activeTicks)*50);check('Holding the real refill control moves finite gas at a paid powered port');
 await click('#resume');const moved=(await state()).activeTicks;await page.evaluate(()=>window.__vireon.teleport(45,40,1.57,-.1));await page.waitForFunction(n=>window.__vireon.getState().activeTicks>n,moved);await selectStation(d);await connect('cable',gen,d);await connect('gas_pipe',e,d);await click('#close-production');
 await configure(()=>{const s=window.__vireon.snapshot();const b=s.world.base.buildings.find(b=>b.kind==='dome');b.zone.q=600000;b.zone.purity=.8;b.zone.temperature=20;const gen=s.world.base.buildings.find(b=>b.kind==='biogenerator');gen.enabled=false;gen.energy=0;s.player.x=48;s.player.z=43;s.player.y=.62;window.__vireon.setState(s);});
 await selectStation(dome);assert.match(await page.locator('#production-status').textContent(),/Герметичен · 48 м³/);await page.getByRole('button',{name:'Пройти шлюз · 6 с',exact:true}).click();assert.equal((await snapshot()).world.base.passage.direction,'in');await page.waitForFunction(()=>!window.__vireon.getState().base.passage);assert.ok(Math.abs((await state()).position.z-41)<.1);const airBefore=await snapshot();await page.waitForFunction(n=>window.__vireon.getState().activeTicks>n+25,airBefore.meta.activeTicks);const airAfter=await snapshot();assert.equal(airAfter.player.bottles[0].milliGU,airBefore.player.bottles[0].milliGU);assert.ok(airAfter.world.base.buildings.find(b=>b.kind==='dome').zone.q<airBefore.world.base.buildings.find(b=>b.kind==='dome').zone.q);check('Six-second manual airlock enters the sealed dome, whose finite air protects through an outage');
 await page.screenshot({path:'artifacts/s2-dome-panel.png'});await click('#close-production');await page.screenshot({path:'artifacts/s2-dome-interior.png'});await pause();await page.evaluate(()=>window.__vireon.save());const persisted=await snapshot();await reopen();const reload=await snapshot();assert.equal(reload.world.base.links.length,persisted.world.base.links.length);assert.equal(reload.world.base.buildings.length,persisted.world.base.buildings.length);assert.ok(reload.world.base.buildings.find(b=>b.kind==='dome').zone.q<=persisted.world.base.buildings.find(b=>b.kind==='dome').zone.q);check('Built shells, links, remaining fuel and room air survive actual IndexedDB reload');
 }else{await configure(async()=>{const {makeBuilding}=await import('/src/game/production.ts');const s=window.__vireon.snapshot();makeBuilding(s,'dome',48,.62,40);s.player.x=48;s.player.y=.62;s.player.z=41;window.__vireon.setState(s);});dome=(await snapshot()).world.base.buildings[0].id;}
 await page.setViewportSize({width:667,height:320});await page.waitForFunction(()=>document.getElementById('world').clientWidth===innerWidth&&document.getElementById('world').clientHeight===innerHeight);await selectStation(dome);await page.waitForTimeout(350);for(const tab of ['recipes','build','links']){await click('#production-'+tab);const tooSmall=await page.locator('#production-panel button:visible').evaluateAll(es=>es.map(e=>({name:e.textContent,rect:e.getBoundingClientRect()})).filter(({rect})=>rect.width<31.99||rect.height<31.99).map(({name})=>name));assert.deepEqual(tooSmall,[]);const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.right>innerWidth+.5||r.left<-.5);}).slice(0,12).map(e=>({id:e.id,cls:e.className,left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right}))}));assert.ok(overflow.scroll<=overflow.width,JSON.stringify({tab,...overflow}));}await page.screenshot({path:'artifacts/s2-production-compact.png'});check('All production tabs fit 667×320 with buttons at least 32×32 CSS px');
 assert.deepEqual(report.errors,[]);check('No runtime or console errors across the production story');
}catch(e){report.failure=e.stack;throw e;}finally{await writeFile('artifacts/s2-production-verification.json',JSON.stringify(report,null,2)+'\n');await browser?.close();await server.close();}
